spring.application.name=aid_compass_application

# ssl
#server.port=8443
#server.ssl.key-store=classpath:/ssl/springboot_keystore.p12
#server.ssl.key-store-password=password
#server.ssl.key-password=password

# postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/api_postgresql_database
spring.datasource.username=admin
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

# jwt
aid.compass.jwt.secret=fji2nr1r-dkr43e-34ind

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=your_username
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true