version: "3.8"
services:
  aid-compass-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    image: aid-compass-api
    env_file:
      - .docker-env

  postgresql:
    image: postgres:16.1-alpine3.19
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: aid_compass_database
    ports:
      - "5432:5432"

  redis:
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    networks:
      - default
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_token.txt:/etc/prometheus/prometheus_token.txt
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    networks:
      - default
    ports:
      - "3000:3000"

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

networks:
  default: