version: "3.8"
services:
  aid-compass-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    image: aid-compass-api
    env_file:
      - .docker-env

  postgresql:
    image: postgres:16.1-alpine3.19
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: aid_compass_database
    ports:
      - "5432:5432"

  redis:
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    networks:
      - default
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_token.txt:/etc/prometheus/prometheus_token.txt
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    networks:
      - default
    ports:
      - "3000:3000"

networks:
  default: