spring.application.name=message-service

# ssl
server.port=8444
server.ssl.key-store=classpath:/ssl/springboot_keystore.p12
server.ssl.key-store-password=password
server.ssl.key-password=password

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redisroot

# company mail
spring.mail.username=
spring.mail.password=

# auth service
api.auth.uri=https://localhost:8443/api/users

api.contacts.uri=https://localhost:8443/api/v1/contacts

# ttl confirm token and cached unconf user
api.conf.account.email.uri=https://localhost:8443/api/confirmations/linked-email?token=
api.conf.account.rsrc.token.ttl.secs=600

api.conf.email.uri=https://localhost:8443/api/confirmations/resource?token=5%s?resource_type=%s
api.conf.rsrc.token.ttl.secs=300

# ttl pass recovery token
api.pass.recovery.email.uri=https://localhost:8443/api/users/recover-password/?token=
api.pass.recovery.token.ttl.secs=300