scrape_configs:
  - job_name: 'aid-compass-backend'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/api/system/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8443']
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/prometheus_token.txt