scrape_configs:
  - job_name: 'aid-compass-backend'
    metrics_path: '/api/system/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8443']
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/prometheus_token.txt