spring.application.name=aid-compass

# ssl
server.port=8444
server.ssl.key-store=classpath:/ssl/springboot_keystore.p12
server.ssl.key-store-password=password
server.ssl.key-password=password

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.password=redisroot

# company mail
spring.mail.username=s2kr49@gmail.com
spring.mail.password=hmdb iowi nuve jnmt

aid.compass.messaging.api.user.service.uri=https://localhost:8443/api/users

# ttl confirm token and cached unconf user
aid.compass.messaging.api.confirm.email.url=https://localhost:8443/api/users/confirm/email?token=
aid.compass.messaging.api.confirm.ttl.secs=300

# ttl pass recovery token
aid.compass.messaging.api.password.recovery.email.url=https://localhost:8443/api/users/recover-password/?token=
aid.compass.messaging.api.password.recovery.ttl.secs=300