aid.compass.messaging.api.user.service.uri=https://localhost:8443/api/users

# ttl confirm token and cached unconf user
aid.compass.messaging.api.confirm.email.url=https://localhost:8443/api/users/confirm/email?token=
aid.compass.messaging.api.confirm.ttl.secs=300

# ttl pass recovery token
aid.compass.messaging.api.password.recovery.email.url=https://localhost:8443/api/users/recover-password/?token=
aid.compass.messaging.api.password.recovery.ttl.secs=300